# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build mod jar

on:
  [workflow_dispatch, push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - uses: gradle/gradle-build-action@v2.9.0
      with:
        gradle-version: 8.6
      name: Set up Gradle
    - name: Add permission
      run: chmod +x ./gradlew
    - name: Execute Gradle build
      run: ./gradlew build
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        path: build/libs
